title = "A test tasks dictionary"
start_day = 2024-01-01
notes = "This is a test tasks TOML file used to check the functionality of the tomltasks class implemented in tomlgantt.py. It is also intended to show all the implemented features."

[group_1]
g_name="Group 1"
notes="Notes about the group of tasks."
[subgruop_1-1]
g_name="Subgroup 1.1"
notes="Those are notes associated to the subgroup."
task_1 = {name="task 1", duration="2 weeks", assignee="Alice", notes="A task is any dictionary in the tree having a name and a duration/due date."}
task_2 = {name="task 2", due=2024-09-01, assignee="Bob", notes="In this case the duration is not specified, but a date due to the task need to be completed is given."}
[subgruop_1-2]
g_name="Subgroup 1.2"
task_3 = {name="task 3", duration="2 weeks", assignee="Alice", deps=["task_1"], notes="Tasks can have a dependance to another, regulating the start day."}
task_4 = {name="task 4", due=2024-09-01, assignee="Bob"}
[group_2]
task_g2={name="task group 2", duration="1 month", assignee="Charlie", notes="A task can be placed anywhere in the tree."}
[subgruop_2-1]
g_name="Subgroup 2.1"
task_3 = {name="task 5", duration="2 weeks", assignee="Alice", milestone=true, notes="A task can be marked as milestone."}
task_4 = {name="task 6", due=2024-09-01, assignee="Bob"}
[subgruop_2-2]
g_name="Subgroup 2.2"
task_3 = {name="task 7", duration="2 weeks", assignee="Alice"}
task_4 = {name="task 8", due=2024-09-01, assignee="Bob"}
